language: php
php:
  - '5.6'
  - '7.0'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script:
  - phpunit --coverage-text

notifications:
  email: dev@geyer.io