Ciscaja\Uhsa\UserBundle\Entity\Role:
  type: entity
  table: ciscaja_uhsa_roles
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    role:
      type: string
      length: 256
      unique: true
    flags:
      type: integer
      options:
        unsigned: true
  manyToMany:
    users:
      targetEntity: Ciscaja\Uhsa\UserBundle\Entity\User
      mappedBy: roles
      cascade: ["persist"]